### ISSUE TITLE
Create a Mnesia wrapper

### ISSUE THREAD

**Issue by oubiwann** [lfex/dragon#14]
Mnesia will be used as the default database in v0. 
- [x] Let's make a nice, Lispy wrapper for it
- [ ] Let's update (and complete) the Mnesia LFE tutorial 
- [ ] Let's make a new copy of the tutorial for use by the new wrapper

**Comment by yurrriq** [comment]
Perhaps useful, even if only ideologically: https://github.com/tapsters/cocktail

**Comment by yurrriq** [comment]
We might borrow some ideas from [cocktail](https://github.com/tapsters/cocktail).

**Comment by oubiwann** [comment]
If we ever do this, it will probably be in another repo (maybe not even a dragon repo).
