### ISSUE TITLE
servant is inspirational 

### ISSUE THREAD

**Issue by yurrriq** [lfex/dragon#15]
I'm not sure where else to put this, but maybe we can steal some ideas, both [code](https://github.com/haskell-servant/servant) and [documentation](http://haskell-servant.readthedocs.org), from [servant](https://github.com/haskell-servant).

**Comment by oubiwann** [comment]
Yeah, the docs they use are built using Sphinx (which uses .rst by default, but I think there's a complicated work-around folks can use if they want to write their docs in Markdown). I'm not the biggest fan of Sphinx, but it's definitely one of the better docs-generators (in the user-guide vein) out there.
