### ISSUE TITLE
Create an LFE-based Slate replacement

### ISSUE THREAD

**Issue by oubiwann** [lfex/dragon#16]
## Goal

Provide any LFE project with an easy-to-use tool for generating project user guides and manuals. Slate is what we've been using for various LFE project user guides but a better general example is the Sphinx project (what's used at [readthedocs.org](readthedocs.org).
## Motivation

Terrible experiences with Ruby-based documentation generation tools. Last-straw sort of thing.
## Dragon Component

This will be just one of the several Dragon components that will eventually be created (including a more general static site generator).
## Familiar Bits

LFE itself is the most esoteric part of this. Everything else will be quite familiar to web devs everywhere:
- Markdown
- Bootstrap
- sass
- Font Awesome
- jQuery (Bootstrap dependency)
- highlight.js
## Background

Even though Slate is what we've been using, it's really only a super-good fit for docs that support multiple languages (e.g., REST API docs), as the content remains the same, but the code examples change from one to the other.

That's not our use case. Ours is user/developer documentation of libraries -- not API reference (for that we use lodox), but rather for use guides. This topic was explored in this LFE docs ticket: https://github.com/lfe/docs/issues/36.

Some thoughts:
- Gitbook is good for when creating books that you want to have in multiple formats
- [Sphinx](http://www.sphinx-doc.org/en/stable/) is what power [ReadTheDocs](https://docs.readthedocs.org/en/latest/getting_started.html#write-your-docs). Python-based, it has a much better history of release stability than what I've seen in Ruby projects, but ReadTheDocs needs docs written in .rst format, not .md. Also, I'm not a fan of the [Sphinx themes](http://www.sphinx-doc.org/en/stable/theming.html#using-a-theme).
- [This repo](https://github.com/PharkMillups/beautiful-docs) provides a list of "beautiful docs". 
  - Some of the best listed there are:
    - http://getbootstrap.com/getting-started/
    - http://dev.librato.com/ (Slate-like; built with Sphinx)
    - https://developer.github.com/v3/
    - http://docs.basho.com/riak/kv/2.1.4/developing/getting-started/erlang/querying/
    - https://docs.djangoproject.com/en/
    - https://stripe.com/docs
    - http://docs.pylonsproject.org/en/latest/docs/pyramid.html (built with Sphinx)
  - Ones that aren't _too_ bad:
    - http://www.dropwizard.io/0.9.2/docs/getting-started.html
    - https://www.linode.com/docs/getting-started
    - https://developer.mozilla.org/en-US/docs/Mozilla/Adding_a_new_event
    - http://developer.postmarkapp.com/developer-api-overview.html
    - http://dexy.github.io/dexy/
- Non-free (USD 99) theme from Twitter Bootstrap is probably one of my favourites: http://bootstrap-themes.github.io/dashboard/docs/index.html -- _very_ beautiful
- Another Slate-like doc solution: [FlatDoc](http://ricostacruz.com/flatdoc/)

**Comment by yurrriq** [comment]
Here we go! I updated the comment so the nested lists render correctly btw.

**Comment by yurrriq** [comment]
[LambdaPad](https://github.com/gar1t/lambdapad) (via lfe/blog#4) looks like it might be a good starting point.
