### ISSUE TITLE
Select an Exemplar-friendly Templating engine

### ISSUE THREAD

**Issue by oubiwann** [lfex/dragon#3]
This may require extending Exemplar to support templating ...

**Comment by yurrriq** [comment]
[enlive](https://github.com/cgrand/enlive) ([example](https://github.com/clojure-cookbook/clojure-cookbook/blob/master/07_webapps/7-11_enlive.asciidoc)) and [Selmer](https://github.com/yogthos/Selmer) ([example](https://github.com/clojure-cookbook/clojure-cookbook/blob/master/07_webapps/7-12_templating-with-selmer.asciidoc)) are related projects in Clojure land.

**Comment by oubiwann** [comment]
Going to go the same route as the LFE site: ErlyDTL (like Selmer, a Django-template clone).
